# Select optimization (-O or -g). -O will be automatically bumped up to the 
# highest level of optimization the compiler supports. If want something in
# between then specify the exact level you want, e.g., -O1 or -O2
OptLevel := -g

##############################################################################
# You should not need to edit below this line.
##############################################################################
# The location of the customized Makefiles
# also inherited from the parent Makefile
export CoinDir = $(shell cd ../..; pwd)
export MakefileDir := $(CoinDir)/Makefiles
include ${MakefileDir}/Makefile.coin
include ${MakefileDir}/Makefile.location

IncDir := ${ClpIncDir} ${CoinIncDir} ${bzlibIncDir} ${zlibIncDir}
LibDir := ${ClpLibDir} ${CoinLibDir} ${bzlibLibDir} ${zlibLibDir}
LibName := ${ClpLibName} ${CoinLibName} ${bzlibLibName} ${zlibLibName}
Define := ${ClpDefine} ${CoinDefine} ${bzlibDefine} ${zlibDefine}

##############################################################################
# You should not need to edit below this line.
##############################################################################

CXXFLAGS += $(OPTFLAG) 
CXXFLAGS += -DUSE_PRESOLVE
CXXFLAGS += -DCLP_IDIOT
# Pick up any include files in Test
CXXFLAGS += -I.
#ifeq ($(OPTFLAG),-g)
#    CXXFLAGS += -DCLP_DEBUG -DPRESOLVE_SUMMARY=1 
#endif

TESTSRC := ClpMain.cpp
TESTSRC += unitTest.cpp
TESTSRC += MyMessageHandler.cpp

###############################################################################

space:= $(empty) $(empty)
OptVersion := $(subst $(space),_,$(OptLevel))

TARGETDIR := $(UNAME)$(OptVersion)
DEPDIR := dep

VPATH := . : include : Junk : ${TARGETDIR} : ${DEPDIR}

#########################################################################

CXXFLAGS += $(addprefix -I,${IncDir})
CXXFLAGS += $(addprefix -D,${Define})

LIBDIRS := ${LibDir}
LIBS    := ${LibName}

LDFLAGS := $(addprefix -L,$(LIBDIRS))
LDFLAGS += $(call ifprefix,$(SHLINKPREFIX),$(LIBDIRS))
LDFLAGS += $(patsubst lib%,-l%,$(basename $(LIBS)))

ifeq ($(findstring Linux,${UNAME}),Linux)
	CXXFLAGS +=	-DREADLINE
	LDFLAGS += -lhistory -lreadline -ltermcap
endif
#LDFLAGS += -lefence
#LDFLAGS += -static
CXXFLAGS += -pg
#if DENSE and using ATLAS
#LDFLAGS += -L/home/forrest/ATLAS/lib/Linux_P4SSE2 -llapack -lcblas -latlas -lf77blas -lg2c
#if DENSE and using given libraries
LDFLAGS += -llapack -lblas -lg2c

###############################################################################

TESTOBJ := $(addprefix $(TARGETDIR)/, $(TESTSRC:.cpp=.o))
TESTDEP := $(addprefix $(DEPDIR)/, $(TESTSRC:.cpp=.d))

###############################################################################
# This one must be right before the rules

include ${MakefileDir}/Makefile.rules

###############################################################################

.DELETE_ON_ERROR:

.PHONY: unitTest

unitTest: $(TARGETDIR)/clp

$(TARGETDIR)/clp : $(TESTOBJ)
	@rm -rf Junk
	@echo ""
	@echo Creating clp
	@mkdir -p $(TARGETDIR)
	@rm -f $@
	$(CXX) $(CXXFLAGS) -o $@ $(TESTOBJ) $(LDFLAGS) $(SYSLD) -lm
	${CP} $@ ..

###############################################################################

%::
	@mkdir -p Junk
	touch Junk/$(notdir $@)

###############################################################################

-include $(TESTDEP)
