# ref: https://github.com/actions/runner-images
name: amd64 Windows

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        cmake: [
          {generator: "Visual Studio 17 2022", config: Release, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
          {generator: "Visual Studio 17 2022", config: Debug, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
        ]
      fail-fast: false
    name: Windows • ${{ matrix.cmake.generator }} (${{ matrix.cmake.config }})
    runs-on: windows-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Check cmake
        run: |
          cmake --version
          cmake -G || true
      - name: Install CoinUtils
        run: >
          git clone -b stable/2.11 --depth=1 https://github.com/Mizux/CoinUtils.git
          && cd CoinUtils
          && cmake -S. -Bbuild
          && cmake --build build --config ${{ matrix.cmake.config }}
          && cmake --build build --config ${{ matrix.cmake.config }} --target install
          && cd ..
          && Remove-Item CoinUtils -Recurse -Include *.*
      - name: Install Osi
        run: >
          git clone -b stable/0.108 --depth=1 https://github.com/Mizux/Osi.git
          && cd Osi
          && cmake -S. -Bbuild
          && cmake --build build --config ${{ matrix.cmake.config }}
          && cmake --build build --config ${{ matrix.cmake.config }} --target install
          && cd ..
          && Remove-Item Osi -Recurse -Include *.*
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "${{ matrix.cmake.generator }}"
          -DCMAKE_CONFIGURATION_TYPES=${{ matrix.cmake.config }}
          -DBUILD_DEPS=ON
          -DCMAKE_INSTALL_PREFIX=build/install
      - name: Build
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target ${{ matrix.cmake.build_target }}
          -v -j2
      - name: Test
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target ${{ matrix.cmake.test_target }}
          -v
      - name: Install
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target ${{ matrix.cmake.install_target }}
          -v
