# ref: https://github.com/actions/runner-images
name: amd64 Linux

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
       matrix:
         cmake: [
           {generator: "Unix Makefiles", config: "Release"},
           {generator: "Ninja", config: "Release"},
           {generator: "Ninja Multi-Config", config: "Release"},
         ]
       fail-fast: false
    name: Linux • ${{ matrix.cmake.generator }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Check cmake
        run: cmake --version
      - name: Install CoinUtils
        run: >
          cd /tmp
          && git clone -b stable/2.11 --depth=1 https://github.com/Mizux/CoinUtils.git
          && cd CoinUtils
          && cmake -S. -Bbuild
          && cmake --build build --config Release
          && sudo cmake --build build --config Release --target install
          && cd ..
          && rm -rf CoinUtils
      - name: Install Osi
        run: >
          cd /tmp
          && git clone -b stable/0.108 --depth=1 https://github.com/Mizux/Osi.git
          && cd Osi
          && cmake -S. -Bbuild
          && cmake --build build --config Release
          && sudo cmake --build build --config Release --target install
          && cd ..
          && rm -rf Osi
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "${{ matrix.cmake.generator }}"
          -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
          -DCMAKE_INSTALL_PREFIX=build/install
      - name: Build
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target all
          -v -j2
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target test
          -v
      - name: Install
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target install
          -v
